export default [
    {
        id:"1",
        img:"propic.png",
        name:"provola",
        description:"ciaone",
        price:30.5,
        cart:false
    },
    {
        id:"2",
        img:"propic.png",
        name:"provola",
        description:"ciao",
        price:40,
        cart:false
    },
    {
        id:"3",
        img:"propic.png",
        name:"provola",
        description:"ciao",
        price:30.5,
        cart:false
    },
    {
        id:"4",
        img:"propic.png",
        name:"provola",
        description:"ciao",
        price:30.5,
        cart:true
    },
    {
        id:"5",
        img:"propic.png",
        name:"provola",
        description:"ciao",
        price:30.5,
        cart:false
    }
]